# Generated by Django 3.2.9 on 2021-11-04 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Cinema Address')),
                ('city', models.TextField(verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='Hall Capacity')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingAPI.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.TextField(verbose_name='Todos')),
                ('movie_details', models.TextField(null=True, verbose_name='Additional data')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.TimeField(verbose_name='Show Time')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingAPI.cinema')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingAPI.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingAPI.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(verbose_name='Seat Type')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingAPI.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingAPI.cinema')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingAPI.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingAPI.movie')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingAPI.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingAPI.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
