# Generated by Django 3.2.9 on 2021-11-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='City Name')),
                ('state', models.TextField(null=True, verbose_name='State')),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.TextField(verbose_name='Movie Name'),
        ),
    ]
