# Generated by Django 3.2.9 on 2021-11-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPI', '0002_auto_20211104_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingAPI.city'),
        ),
    ]
