# Generated by Django 3.2.9 on 2021-11-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPI', '0003_alter_cinema_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='hall_name',
            field=models.TextField(default=1, verbose_name='Hall name'),
            preserve_default=False,
        ),
    ]
