# Generated by Django 3.2.9 on 2021-11-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPI', '0004_hall_hall_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='seat_id',
            new_name='seat',
        ),
    ]
