# Generated by Django 3.2.9 on 2021-11-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingAPI', '0005_rename_seat_id_booking_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name='Is Booking confirmed'),
            preserve_default=False,
        ),
    ]
